"""
AI Command Executor
This module contains the logic to execute commands generated by the AI assistant.
"""
import json
from typing import Dict, Any


def execute_ai_command(command_json: Dict[str, Any], api_all_create_func, api_delete_func, api_aws_delete_func, api_list_get_func, api_aws_list_get_func, log_telegram_func, credentials_path: str) -> Dict[str, Any]:
    """
    Execute a command generated by the AI.
    
    Args:
        command_json: Dictionary with 'command', 'parameters', and 'explanation'
        api_all_create_func: Function to create clusters
        api_delete_func: Function to delete GCP instances
        api_aws_delete_func: Function to delete AWS instances
        api_list_get_func: Function to list GCP instances
        api_aws_list_get_func: Function to list AWS instances
        log_telegram_func: Function to log to Telegram
        credentials_path: Path to GCP credentials file
    
    Returns:
        Dictionary with execution result
    """
    command = command_json.get("command")
    parameters = command_json.get("parameters", {})
    explanation = command_json.get("explanation", "")
    
    log_telegram_func(f"🤖 AI Command Execution: {command}\n{explanation}")
    
    if command == "create_cluster":
        # Map AI parameters to request format
        cluster_type = parameters.get("cluster_type", "docker-swarm-manager")
        total_nodes = parameters.get("total_nodes", 2)
        
        gcp_params = parameters.get("gcp", {})
        aws_params = parameters.get("aws", {})
        
        request_data = {
            "cluster_type": cluster_type,
            "total_nodes": total_nodes
        }
        
        if gcp_params:
            request_data["gcp"] = {
                "name": gcp_params.get("name", "ai-gcp-cluster"),
                "zone": gcp_params.get("zone", "europe-west1-b"),
                "machine_type": gcp_params.get("machine_type", "e2-medium"),
                "count": total_nodes // 2 if total_nodes else 1
            }
        
        if aws_params:
            request_data["aws"] = {
                "name": aws_params.get("name", "ai-aws-cluster"),
                "region": aws_params.get("region", "us-west-2"),
                "instance_type": aws_params.get("instance_type", "t3.micro"),
                "min_count": total_nodes - (total_nodes // 2) if total_nodes else 1,
                "max_count": total_nodes - (total_nodes // 2) if total_nodes else 1
            }
        
        # Execute the creation
        from main import AllCreateRequest
        req = AllCreateRequest(**request_data)
        result = api_all_create_func(req)
        
        return {
            "success": True,
            "command": command,
            "explanation": explanation,
            "result": result
        }
    
    elif command == "delete_instance":
        # Handle delete command
        gcp_name = parameters.get("gcp_name")
        aws_name = parameters.get("aws_name")
        instances = parameters.get("instances", [])
        
        results = {}
        
        # Handle list of instances
        if instances:
            for inst in instances:
                inst_name = inst.get("name")
                provider = inst.get("provider", "gcp")  # Default to GCP
                
                if provider == "gcp":
                    try:
                        from main import DeleteRequest
                        delete_req = DeleteRequest(
                            credentials=credentials_path,
                            name=inst_name
                        )
                        results[f'gcp_{inst_name}'] = api_delete_func(delete_req)
                    except Exception as e:
                        results[f'gcp_{inst_name}'] = {"error": str(e)}
                elif provider == "aws":
                    try:
                        from main import AwsDeleteRequest
                        delete_req = AwsDeleteRequest(name=inst_name)
                        results[f'aws_{inst_name}'] = api_aws_delete_func(delete_req)
                    except Exception as e:
                        results[f'aws_{inst_name}'] = {"error": str(e)}
        
        # Handle individual GCP/AWS names
        if gcp_name:
            try:
                from main import DeleteRequest
                delete_req = DeleteRequest(
                    credentials=credentials_path,
                    name=gcp_name
                )
                results['gcp'] = api_delete_func(delete_req)
            except Exception as e:
                results['gcp'] = {"error": str(e)}
        
        if aws_name:
            try:
                from main import AwsDeleteRequest
                delete_req = AwsDeleteRequest(name=aws_name)
                results['aws'] = api_aws_delete_func(delete_req)
            except Exception as e:
                results['aws'] = {"error": str(e)}
        
        return {
            "success": True,
            "command": command,
            "explanation": explanation,
            "result": results
        }
    
    elif command == "list_instances":
        # Handle list command
        gcp_instances = api_list_get_func()
        aws_instances = api_aws_list_get_func()
        
        return {
            "success": True,
            "command": command,
            "explanation": explanation,
            "result": {
                "gcp": gcp_instances,
                "aws": aws_instances
            }
        }
    
    else:
        raise ValueError(f"Unknown command: {command}")
